/*
 * Copyright (c) 2018 Spyder Innovations </Akila Ranasinghe>
 * All rights reserved.
 */
package Views;

import Ctrl.JDBC;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author AKILA
 */
public class Customer_Confirm extends javax.swing.JDialog {

    /**
     * Creates new form Customer_Confirm
     *
     * @param parent
     * @param modal
     */
    String accessType;

    public Customer_Confirm(java.awt.Frame parent, boolean modal, String AccType) {
        super(parent, modal);
        initComponents();
        accessType = AccType;
        btn_ModeNFC.doClick();
        Home.subWindowName = "custConfirmation";
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_background = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/Images/background.png"));
                    image = ii.getImage();
                }catch(Exception e){
                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        Panel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Panel_tapNFC = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_nfcID = new javax.swing.JPasswordField();
        btn_nfcLogin = new javax.swing.JButton();
        btn_ModePsw = new javax.swing.JButton();
        Panel_PSW = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        txt_userName = new javax.swing.JTextField();
        btn_ModeNFC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Panel_header.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel1.setText("Login");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Customer");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));

        javax.swing.GroupLayout Panel_headerLayout = new javax.swing.GroupLayout(Panel_header);
        Panel_header.setLayout(Panel_headerLayout);
        Panel_headerLayout.setHorizontalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_headerLayout.setVerticalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        Panel_tapNFC.setOpaque(false);

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NFCdevice.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Please Tap NFC Card For Identification");

        txt_nfcID.setEditable(false);
        txt_nfcID.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_nfcID.setForeground(new java.awt.Color(0, 102, 102));

        btn_nfcLogin.setBackground(new java.awt.Color(0, 125, 184));
        btn_nfcLogin.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btn_nfcLogin.setForeground(new java.awt.Color(255, 255, 255));
        btn_nfcLogin.setText("Login");
        btn_nfcLogin.setContentAreaFilled(false);
        btn_nfcLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nfcLogin.setOpaque(true);
        btn_nfcLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nfcLoginActionPerformed(evt);
            }
        });

        btn_ModePsw.setBackground(new java.awt.Color(42, 42, 42));
        btn_ModePsw.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        btn_ModePsw.setForeground(new java.awt.Color(255, 255, 255));
        btn_ModePsw.setText("###");
        btn_ModePsw.setContentAreaFilled(false);
        btn_ModePsw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ModePsw.setOpaque(true);
        btn_ModePsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModePswActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_tapNFCLayout = new javax.swing.GroupLayout(Panel_tapNFC);
        Panel_tapNFC.setLayout(Panel_tapNFCLayout);
        Panel_tapNFCLayout.setHorizontalGroup(
            Panel_tapNFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_tapNFCLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(Panel_tapNFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_tapNFCLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ModePsw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_nfcLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nfcID)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_tapNFCLayout.setVerticalGroup(
            Panel_tapNFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_tapNFCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_tapNFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_tapNFCLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nfcID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_tapNFCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_nfcLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ModePsw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8))
                .addGap(0, 0, 0))
        );

        Panel_PSW.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel3.setText("Password");

        txt_password.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txt_password.setForeground(new java.awt.Color(0, 102, 102));
        txt_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passwordKeyPressed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 125, 184));
        btn_login.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.setContentAreaFilled(false);
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.setOpaque(true);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txt_userName.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txt_userName.setForeground(new java.awt.Color(0, 102, 102));
        txt_userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userNameKeyPressed(evt);
            }
        });

        btn_ModeNFC.setBackground(new java.awt.Color(42, 42, 42));
        btn_ModeNFC.setFont(new java.awt.Font("Open Sans", 1, 10)); // NOI18N
        btn_ModeNFC.setForeground(new java.awt.Color(255, 255, 255));
        btn_ModeNFC.setText("o))");
        btn_ModeNFC.setContentAreaFilled(false);
        btn_ModeNFC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ModeNFC.setOpaque(true);
        btn_ModeNFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModeNFCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_PSWLayout = new javax.swing.GroupLayout(Panel_PSW);
        Panel_PSW.setLayout(Panel_PSWLayout);
        Panel_PSWLayout.setHorizontalGroup(
            Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PSWLayout.createSequentialGroup()
                .addGap(42, 62, Short.MAX_VALUE)
                .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_PSWLayout.createSequentialGroup()
                        .addComponent(btn_ModeNFC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_PSWLayout.createSequentialGroup()
                        .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_userName, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txt_password))))
                .addContainerGap())
        );

        Panel_PSWLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3});

        Panel_PSWLayout.setVerticalGroup(
            Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PSWLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_PSWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_ModeNFC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_PSWLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel2, jLabel3, txt_password});

        Panel_PSWLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_ModeNFC, btn_login});

        javax.swing.GroupLayout Panel_backgroundLayout = new javax.swing.GroupLayout(Panel_background);
        Panel_background.setLayout(Panel_backgroundLayout);
        Panel_backgroundLayout.setHorizontalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_tapNFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_PSW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_backgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Panel_PSW, Panel_tapNFC});

        Panel_backgroundLayout.setVerticalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addComponent(Panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_tapNFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Panel_PSW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_userNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userNameKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_password.grabFocus();
        }
    }//GEN-LAST:event_txt_userNameKeyPressed

    private void txt_passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passwordKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_login.doClick();
        }
    }//GEN-LAST:event_txt_passwordKeyPressed

    private void btn_ModePswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModePswActionPerformed

        Panel_PSW.setVisible(true);
        Panel_tapNFC.setVisible(false);

    }//GEN-LAST:event_btn_ModePswActionPerformed

    private void btn_ModeNFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModeNFCActionPerformed

        Panel_tapNFC.setVisible(true);
        Panel_PSW.setVisible(false);

    }//GEN-LAST:event_btn_ModeNFCActionPerformed

    private void btn_nfcLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nfcLoginActionPerformed

        try {
            // check nfc field is empty OR not
            if (txt_nfcID.getText().toString().trim().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Please tap NFC Card.");
                txt_nfcID.setText(null);
                txt_nfcID.grabFocus();
            } else {
                // check nfc is available to login
                ResultSet r = JDBC.getData("SELECT * FROM customer WHERE nfc_id = '" + txt_nfcID.getText().toString().trim() + "'  ");
                if (r.next()) {
                    if (r.getString("status").equals("Active")) {
                        this.dispose();
                        // open requested accessType Frame
                        if (accessType.equals("AccDetails")) {
                            Home.subWindowName = "";
                            new Customer_AccountDetails(null, true, r.getString("customer_id")).setVisible(true);
                            Home.subWindowName = "";
                        } else if (accessType.equals("Reload")) {
                            Home.subWindowName = "";
                            new Customer_Reload(null, true, r.getString("customer_id"), new DecimalFormat("#0.00").format(r.getDouble("balance"))).setVisible(true);
                            Home.subWindowName = "";
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Account had been deactivated.", "Access Denied", 2);
                        txt_nfcID.setText(null);
                        txt_nfcID.grabFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Non-Registered NFC Card.", "Access Denied", 2);
                    txt_nfcID.setText(null);
                    txt_nfcID.grabFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_nfcLoginActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        try {
            // create new variable for inserted User Name & Password
            String user = txt_userName.getText();
            String password = new String(txt_password.getPassword());

            String emptyVariable = "";
            // check text fields are empty OR not
            if (user.equals(emptyVariable) && password.equals(emptyVariable)) {
                JOptionPane.showMessageDialog(rootPane, "Please insert valid user name & password.");
                txt_userName.grabFocus();
            } else {
                String UN = "";
                String PS = "";
                // check user name & password is correct to login
                ResultSet r = JDBC.getData("SELECT * FROM customer WHERE user_name = '" + user + "'  ");
                if (r.next()) {
                    UN = r.getString("user_name");
                    PS = r.getString("password");
                }
                if (UN.equals(user) && PS.equals(password)) {
                    if (r.getString("status").equals("Active")) {
                        this.dispose();
                        // open requested accessType Frame
                        if (accessType.equals("AccDetails")) {
                            Home.subWindowName = "";
                            new Customer_AccountDetails(null, true, r.getString("customer_id")).setVisible(true);
                            Home.subWindowName = "";
                        } else if (accessType.equals("Reload")) {
                            Home.subWindowName = "";
                            new Customer_Reload(null, true, r.getString("customer_id"), new DecimalFormat("#0.00").format(r.getDouble("balance"))).setVisible(true);
                            Home.subWindowName = "";
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Account had been deactivated.", "Access Denied", 2);
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Please insert correct user name and password.");
                    txt_userName.grabFocus();
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Customer_Confirm dialog = new Customer_Confirm(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_PSW;
    private javax.swing.JPanel Panel_background;
    private javax.swing.JPanel Panel_header;
    private javax.swing.JPanel Panel_tapNFC;
    private javax.swing.JButton btn_ModeNFC;
    private javax.swing.JButton btn_ModePsw;
    public static javax.swing.JButton btn_login;
    public static javax.swing.JButton btn_nfcLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JPasswordField txt_nfcID;
    public static javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables

}
