/*
 * Copyright (c) 2018 Spyder Innovations </Akila Ranasinghe>
 * All rights reserved.
 */
package Views;

import Ctrl.JDBC;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 * @author AKILA
 */
public class Customer_ManageAccs extends javax.swing.JDialog {

    /**
     * Creates new form Customer_ManageAccs
     *
     * @param parent
     * @param modal
     */
    public Customer_ManageAccs(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadCustomers();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_background = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/Images/background.png"));
                    image = ii.getImage();
                }catch(Exception e){
                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        Panel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Panel_content = new javax.swing.JPanel();
        btn_refresh = new javax.swing.JButton();
        btn_activate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_customers = new javax.swing.JTable();
        btn_deactivate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(null);

        Panel_header.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel1.setText("Manage Accounts");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Customer");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));

        javax.swing.GroupLayout Panel_headerLayout = new javax.swing.GroupLayout(Panel_header);
        Panel_header.setLayout(Panel_headerLayout);
        Panel_headerLayout.setHorizontalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_headerLayout.setVerticalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        Panel_content.setOpaque(false);

        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Ref2.png"))); // NOI18N
        btn_refresh.setContentAreaFilled(false);
        btn_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_refresh.setFocusable(false);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_activate.setBackground(new java.awt.Color(0, 125, 184));
        btn_activate.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        btn_activate.setForeground(new java.awt.Color(255, 255, 255));
        btn_activate.setText("Acivate");
        btn_activate.setContentAreaFilled(false);
        btn_activate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_activate.setFocusPainted(false);
        btn_activate.setFocusable(false);
        btn_activate.setOpaque(true);
        btn_activate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_activateActionPerformed(evt);
            }
        });

        Table_customers.setAutoCreateRowSorter(true);
        Table_customers.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        Table_customers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Name", "Status", "sts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_customers.setRowHeight(18);
        Table_customers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table_customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_customersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table_customers);
        if (Table_customers.getColumnModel().getColumnCount() > 0) {
            Table_customers.getColumnModel().getColumn(3).setMinWidth(0);
            Table_customers.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        btn_deactivate.setBackground(new java.awt.Color(255, 51, 51));
        btn_deactivate.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        btn_deactivate.setForeground(new java.awt.Color(255, 255, 255));
        btn_deactivate.setText("Deactivate");
        btn_deactivate.setContentAreaFilled(false);
        btn_deactivate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_deactivate.setFocusPainted(false);
        btn_deactivate.setFocusable(false);
        btn_deactivate.setOpaque(true);
        btn_deactivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deactivateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_contentLayout = new javax.swing.GroupLayout(Panel_content);
        Panel_content.setLayout(Panel_contentLayout);
        Panel_contentLayout.setHorizontalGroup(
            Panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(Panel_contentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addGroup(Panel_contentLayout.createSequentialGroup()
                        .addComponent(btn_activate)
                        .addGap(0, 0, 0)
                        .addComponent(btn_deactivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Panel_contentLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_activate, btn_deactivate});

        Panel_contentLayout.setVerticalGroup(
            Panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_contentLayout.createSequentialGroup()
                .addGroup(Panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_contentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_activate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_deactivate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_backgroundLayout = new javax.swing.GroupLayout(Panel_background);
        Panel_background.setLayout(Panel_backgroundLayout);
        Panel_backgroundLayout.setHorizontalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_backgroundLayout.setVerticalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addComponent(Panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Panel_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed

        loadCustomers();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void Table_customersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_customersMouseClicked

        if (evt.getButton() == MouseEvent.BUTTON1) {
            if (Table_customers.getSelectedRow() != -1) {
                if (Table_customers.getValueAt(Table_customers.getSelectedRow(), 3).toString().equals("Active")) {
                    btn_activate.setVisible(false);
                    btn_deactivate.setVisible(true);
                } else {
                    btn_activate.setVisible(true);
                    btn_deactivate.setVisible(false);
                }
            } else {
                btn_activate.setVisible(false);
                btn_deactivate.setVisible(false);
            }
        }

    }//GEN-LAST:event_Table_customersMouseClicked

    private void btn_activateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_activateActionPerformed

        updateCustomerStatus("Active");
    }//GEN-LAST:event_btn_activateActionPerformed

    private void btn_deactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deactivateActionPerformed

        updateCustomerStatus("Deactive");

    }//GEN-LAST:event_btn_deactivateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_ManageAccs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_ManageAccs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_ManageAccs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_ManageAccs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Customer_ManageAccs dialog = new Customer_ManageAccs(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_background;
    private javax.swing.JPanel Panel_content;
    private javax.swing.JPanel Panel_header;
    private javax.swing.JTable Table_customers;
    private javax.swing.JButton btn_activate;
    private javax.swing.JButton btn_deactivate;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void loadCustomers() {
        try {
            DefaultTableModel dtm = (DefaultTableModel) Table_customers.getModel();
            ResultSet rsCust = JDBC.getData("SELECT * FROM customer ORDER BY f_name ");
            dtm.setRowCount(0);
            while (rsCust.next()) {
                Vector v = new Vector();
                v.add(rsCust.getString("customer_id"));
                v.add(rsCust.getString("f_name") + " " + rsCust.getString("l_name"));
                if (rsCust.getString("status").equals("Active")) {
                    v.add("<html><font color='Green'>Active</font></html>");
                } else {
                    v.add("<html><font color='Red'>Deactive</font></html>");
                }
                v.add(rsCust.getString("status"));
                dtm.addRow(v);
            }

            // set Action buttton
            btn_activate.setVisible(false);
            btn_deactivate.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void updateCustomerStatus(String newStatus) {
        try {
            JDBC.putData(" UPDATE customer SET status = '" + newStatus + "'  WHERE customer_id= '" + Table_customers.getValueAt(Table_customers.getSelectedRow(), 0).toString() + "'  ");
            btn_refresh.doClick();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
