/*
 * Copyright (c) 2018 Spyder Innovations </Akila Ranasinghe>
 * All rights reserved.
 */
package Views;

import Ctrl.Communicator;
import Ctrl.JDBC;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 * @author AKILA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    byte attemp = 0;
    int Xmouse, Ymouse;

    public static String subWindowName = "";

    public static String adminUserID;
    public static Communicator communicator;

    public Home(String adminUid) {
        initComponents();

        adminUserID = adminUid;
        frameExitingPrompt();
        uiConfig();
        openSerialPORTCommService();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_background = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/Images/background.png"));
                    image = ii.getImage();
                }catch(Exception e){
                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        Panel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_minimize = new javax.swing.JButton();
        lbl_deviceOn = new javax.swing.JLabel();
        Panel_customer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCust_accDetails = new javax.swing.JButton();
        btnCust_reload = new javax.swing.JButton();
        btnCust_createNewAcc = new javax.swing.JButton();
        btnCust_manageAcc = new javax.swing.JButton();
        Panel_seller = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSeller_accDetails = new javax.swing.JButton();
        btnSeller_createNewAcc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setUndecorated(true);
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        Panel_header.setBackground(new java.awt.Color(77, 208, 225));

        jLabel1.setBackground(new java.awt.Color(42, 42, 42));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("     C A S H   C A R D   S Y S T  E M");

        btn_exit.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/power-25.png"))); // NOI18N
        btn_exit.setToolTipText("Exit");
        btn_exit.setContentAreaFilled(false);
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_exit.setFocusable(false);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/password-25.png"))); // NOI18N
        jButton1.setText("Change My Password");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_minimize.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize_24.png"))); // NOI18N
        btn_minimize.setToolTipText("Minimize");
        btn_minimize.setContentAreaFilled(false);
        btn_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_minimize.setFocusable(false);
        btn_minimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_minimizeActionPerformed(evt);
            }
        });

        lbl_deviceOn.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        lbl_deviceOn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_deviceOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nfcDevIndicator_32.png"))); // NOI18N

        javax.swing.GroupLayout Panel_headerLayout = new javax.swing.GroupLayout(Panel_header);
        Panel_header.setLayout(Panel_headerLayout);
        Panel_headerLayout.setHorizontalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(lbl_deviceOn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        Panel_headerLayout.setVerticalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_minimize)
                        .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_exit)))
                    .addComponent(jLabel1)
                    .addComponent(lbl_deviceOn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_customer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setText("    Customer");
        jLabel2.setOpaque(true);

        btnCust_accDetails.setBackground(new java.awt.Color(0, 102, 153));
        btnCust_accDetails.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnCust_accDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_accDetails.setText("Account Details");
        btnCust_accDetails.setContentAreaFilled(false);
        btnCust_accDetails.setOpaque(true);
        btnCust_accDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_accDetailsActionPerformed(evt);
            }
        });

        btnCust_reload.setBackground(new java.awt.Color(0, 102, 153));
        btnCust_reload.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnCust_reload.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_reload.setText("Reload");
        btnCust_reload.setContentAreaFilled(false);
        btnCust_reload.setOpaque(true);
        btnCust_reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_reloadActionPerformed(evt);
            }
        });

        btnCust_createNewAcc.setBackground(new java.awt.Color(0, 102, 153));
        btnCust_createNewAcc.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnCust_createNewAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_createNewAcc.setText("Create New Account");
        btnCust_createNewAcc.setContentAreaFilled(false);
        btnCust_createNewAcc.setOpaque(true);
        btnCust_createNewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_createNewAccActionPerformed(evt);
            }
        });

        btnCust_manageAcc.setBackground(new java.awt.Color(0, 102, 153));
        btnCust_manageAcc.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnCust_manageAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_manageAcc.setText("Manage Accounts");
        btnCust_manageAcc.setContentAreaFilled(false);
        btnCust_manageAcc.setOpaque(true);
        btnCust_manageAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_manageAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_customerLayout = new javax.swing.GroupLayout(Panel_customer);
        Panel_customer.setLayout(Panel_customerLayout);
        Panel_customerLayout.setHorizontalGroup(
            Panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_customerLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Panel_customerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCust_accDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCust_reload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCust_manageAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCust_createNewAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        Panel_customerLayout.setVerticalGroup(
            Panel_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnCust_reload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCust_accDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCust_manageAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnCust_createNewAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_seller.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText(" Seller     ");
        jLabel3.setOpaque(true);

        btnSeller_accDetails.setBackground(new java.awt.Color(0, 102, 153));
        btnSeller_accDetails.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnSeller_accDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnSeller_accDetails.setText("Account Details");
        btnSeller_accDetails.setContentAreaFilled(false);
        btnSeller_accDetails.setOpaque(true);
        btnSeller_accDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeller_accDetailsActionPerformed(evt);
            }
        });

        btnSeller_createNewAcc.setBackground(new java.awt.Color(0, 102, 153));
        btnSeller_createNewAcc.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        btnSeller_createNewAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnSeller_createNewAcc.setText("Create New Account");
        btnSeller_createNewAcc.setContentAreaFilled(false);
        btnSeller_createNewAcc.setOpaque(true);
        btnSeller_createNewAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeller_createNewAccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_sellerLayout = new javax.swing.GroupLayout(Panel_seller);
        Panel_seller.setLayout(Panel_sellerLayout);
        Panel_sellerLayout.setHorizontalGroup(
            Panel_sellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_sellerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_sellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeller_accDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeller_createNewAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_sellerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_sellerLayout.setVerticalGroup(
            Panel_sellerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_sellerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(btnSeller_accDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSeller_createNewAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(121, 121, 121))
        );

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nfcreader-256.png"))); // NOI18N
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout Panel_backgroundLayout = new javax.swing.GroupLayout(Panel_background);
        Panel_background.setLayout(Panel_backgroundLayout);
        Panel_backgroundLayout.setHorizontalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(Panel_seller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Panel_backgroundLayout.setVerticalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addComponent(Panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_customer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_seller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeller_createNewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeller_createNewAccActionPerformed

        new Seller_CreateAccount(this, true).setVisible(true);
        uiConfig();
        subWindowName = "";
    }//GEN-LAST:event_btnSeller_createNewAccActionPerformed

    private void btnCust_createNewAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_createNewAccActionPerformed

        new Customer_CreateAccount(this, true).setVisible(true);
        uiConfig();
        subWindowName = "";
    }//GEN-LAST:event_btnCust_createNewAccActionPerformed

    private void btnSeller_accDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeller_accDetailsActionPerformed

        new Seller_ConfirmToAccDetails(this, true).setVisible(true);
        uiConfig();
    }//GEN-LAST:event_btnSeller_accDetailsActionPerformed

    private void btnCust_accDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_accDetailsActionPerformed

        new Customer_Confirm(this, true, "AccDetails").setVisible(true);
        subWindowName = "";
    }//GEN-LAST:event_btnCust_accDetailsActionPerformed

    private void btnCust_reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_reloadActionPerformed

        new Customer_Confirm(this, true, "Reload").setVisible(true);
        subWindowName = "";
    }//GEN-LAST:event_btnCust_reloadActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed

        try {
            int i = JOptionPane.showConfirmDialog(rootPane, "By exiting, Cash Card System will be stopped until your next login.\nAre you sure, you want to exit now ?", "Warning", 0);
            if (i == 0) {
                // ADmin Password Confirmation 4 Exit
                JPasswordField pswField = new JPasswordField();
                int confirmPSW = JOptionPane.showConfirmDialog(rootPane, pswField, "Please Insert Administrator Password", JOptionPane.OK_CANCEL_OPTION);
                if (confirmPSW == 0) { // if yes
                    if (!pswField.getText().toString().trim().isEmpty()) {
                        ResultSet rs = JDBC.getData("SELECT id, password FROM admin WHERE id='" + adminUserID + "' AND password = '" + pswField.getText().toString().trim() + "' ");
                        if (rs.next()) {
                            communicator.disconnect();
                            System.exit(0);
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Invalid Password.", "Access Denied", 2);
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Please Insert Valid Password.", "Access Denied", 2);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btnCust_manageAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_manageAccActionPerformed

        try {
            // ADmin Password Confirmation
            JPasswordField pswField = new JPasswordField();
            int confirmPSW = JOptionPane.showConfirmDialog(rootPane, pswField, "Please Insert Administrator Password", JOptionPane.OK_CANCEL_OPTION);
            if (confirmPSW == 0) { // if yes
                if (!pswField.getText().toString().trim().isEmpty()) {
                    ResultSet rs = JDBC.getData("SELECT id, password FROM admin WHERE id='" + adminUserID + "' AND password = '" + pswField.getText().toString().trim() + "' ");
                    if (rs.next()) {
                        new Customer_ManageAccs(this, true).setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Invalid Password.", "Access Denied", 2);
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Please Insert Valid Password.", "Access Denied", 2);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnCust_manageAccActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new Admin_ChangePassword(this, true).setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_minimizeActionPerformed

        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btn_minimizeActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        Xmouse = evt.getX();
        Ymouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - Xmouse, y - Ymouse);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_background;
    private javax.swing.JPanel Panel_customer;
    private javax.swing.JPanel Panel_header;
    private javax.swing.JPanel Panel_seller;
    private javax.swing.JButton btnCust_accDetails;
    private javax.swing.JButton btnCust_createNewAcc;
    private javax.swing.JButton btnCust_manageAcc;
    private javax.swing.JButton btnCust_reload;
    private javax.swing.JButton btnSeller_accDetails;
    private javax.swing.JButton btnSeller_createNewAcc;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_minimize;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel lbl_deviceOn;
    // End of variables declaration//GEN-END:variables

    private void uiConfig() {
        try {
            // check Customer Account already exist OR not 
            ResultSet rs1 = JDBC.getData(" SELECT customer_id FROM customer ");
            if (rs1.next()) {
                btnCust_accDetails.setEnabled(true);
                btnCust_reload.setEnabled(true);
                btnCust_manageAcc.setEnabled(true);
            } else {
                btnCust_accDetails.setEnabled(false);
                btnCust_reload.setEnabled(false);
                btnCust_manageAcc.setEnabled(false);
            }

            // check  Sellers Account already exist OR not 
            ResultSet rs2 = JDBC.getData(" SELECT payee_account_id FROM payee_account ");
            if (rs2.next()) {
                btnSeller_accDetails.setEnabled(true);
            } else {
                btnSeller_accDetails.setEnabled(false);
            }

            lbl_deviceOn.setVisible(false);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void frameExitingPrompt() {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent evt) {
                try {
                    int i = JOptionPane.showConfirmDialog(rootPane, "By exiting, Cash Card System will be stopped until your next login.\nAre you sure, you want to exit now ?", "Warning", 0);
                    if (i == 0) {
                        // ADmin Password Confirmation 4 Exit
                        JPasswordField pswField = new JPasswordField();
                        int confirmPSW = JOptionPane.showConfirmDialog(rootPane, pswField, "Please Insert Administrator Password", JOptionPane.OK_CANCEL_OPTION);
                        if (confirmPSW == 0) { // if yes
                            if (!pswField.getText().toString().trim().isEmpty()) {
                                ResultSet rs = JDBC.getData("SELECT id, password FROM admin WHERE id='" + adminUserID + "' AND password = '" + pswField.getText().toString().trim() + "' ");
                                if (rs.next()) {
                                    communicator.disconnect();
                                    System.exit(0);
                                } else {
                                    JOptionPane.showMessageDialog(rootPane, "Invalid Password.", "Access Denied", 2);
                                }
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Please Insert Valid Password.", "Access Denied", 2);
                            }
                        }
                    }
                } catch (Exception e) {
                }
            }
        }
        );
    }

    // +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    private void openSerialPORTCommService() {
        try {

            //Communicator object
            communicator = new Communicator();

            // search for  available PORT
            String portName = communicator.searchForPorts();
           // System.out.println("FOUND PORTNAME: " + portName);

            // Connect to available PORT + init PORT Listener
            communicator.connect(portName);
            if (communicator.getConnected() == true) {
                if (communicator.initIOStream() == true) {
                    communicator.initListener();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "NFC Device Not Found.\nPlease check NFC device connection first.", "Communication Faild", 0);
                System.exit(0);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
