/*
 * Copyright (c) 2018 Spyder Innovations </Akila Ranasinghe>
 * All rights reserved.
 */
package Views;

import Ctrl.JDBC;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author AKILA
 */
public class Seller_Withdraw extends javax.swing.JDialog {

    /**
     * Creates new form Seller_Withdraw
     *
     * @param parent
     * @param modal
     * @param payeeID
     * @param balance
     */
    String payeeAccID;
    double AccBalance;

    public Seller_Withdraw(java.awt.Frame parent, boolean modal, String payeeID, String balance) {
        super(parent, modal);
        initComponents();
        payeeAccID = payeeID;
        AccBalance = Double.valueOf(balance);

        txt_AvlAmount.setText(String.valueOf(AccBalance));
        txt_Balance.setText(String.valueOf(AccBalance));
        btn_withdraw.setEnabled(false);
        btn_withdraw.setBackground(new Color(240, 240, 240));

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_background = new javax.swing.JPanel(){
            private Image image;{
                try{
                    ImageIcon ii = new ImageIcon(getClass().getResource("/Images/background.png"));
                    image = ii.getImage();
                }catch(Exception e){
                }
            }
            @Override
            protected void paintComponent(Graphics graphcs){
                super.paintComponent(graphcs);
                graphcs.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        Panel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txt_AvlAmount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_withdraw = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_WithdrawAmount = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Balance = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Panel_header.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel1.setText("Withdraw Money");

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Seller");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));

        javax.swing.GroupLayout Panel_headerLayout = new javax.swing.GroupLayout(Panel_header);
        Panel_header.setLayout(Panel_headerLayout);
        Panel_headerLayout.setHorizontalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_headerLayout.setVerticalGroup(
            Panel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        txt_AvlAmount.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txt_AvlAmount.setForeground(new java.awt.Color(0, 102, 102));
        txt_AvlAmount.setText("0.00");

        jLabel3.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel3.setText("Withdraw Amount");

        btn_withdraw.setBackground(new java.awt.Color(0, 125, 184));
        btn_withdraw.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        btn_withdraw.setForeground(new java.awt.Color(255, 255, 255));
        btn_withdraw.setText("Withdraw");
        btn_withdraw.setContentAreaFilled(false);
        btn_withdraw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_withdraw.setOpaque(true);
        btn_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_withdrawActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText(":       Rs.");

        jLabel6.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel6.setText(":       Rs.");

        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Available Amount");

        txt_WithdrawAmount.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        txt_WithdrawAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_WithdrawAmountFocusLost(evt);
            }
        });
        txt_WithdrawAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_WithdrawAmountKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_WithdrawAmountKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_WithdrawAmountKeyTyped(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(160, 160, 160)));

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Balance");

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText(":       Rs.");

        txt_Balance.setFont(new java.awt.Font("Open Sans", 0, 13)); // NOI18N
        txt_Balance.setForeground(new java.awt.Color(0, 102, 102));
        txt_Balance.setText("0.00");

        jLabel10.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -");

        btn_cancel.setBackground(new java.awt.Color(255, 102, 102));
        btn_cancel.setFont(new java.awt.Font("Open Sans", 1, 13)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_cancel.setText("Cancel");
        btn_cancel.setContentAreaFilled(false);
        btn_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cancel.setOpaque(true);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_backgroundLayout = new javax.swing.GroupLayout(Panel_background);
        Panel_background.setLayout(Panel_backgroundLayout);
        Panel_backgroundLayout.setHorizontalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_backgroundLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Balance, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(Panel_backgroundLayout.createSequentialGroup()
                        .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_AvlAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(txt_WithdrawAmount))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_backgroundLayout.createSequentialGroup()
                        .addComponent(btn_withdraw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel)))
                .addContainerGap())
        );

        Panel_backgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, jLabel7, jLabel8});

        Panel_backgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, jLabel6, jLabel9});

        Panel_backgroundLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_cancel, btn_withdraw});

        Panel_backgroundLayout.setVerticalGroup(
            Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_backgroundLayout.createSequentialGroup()
                .addComponent(Panel_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_AvlAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_WithdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_withdraw)
                    .addComponent(btn_cancel))
                .addContainerGap())
        );

        Panel_backgroundLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel6, jLabel7, jLabel8, jLabel9, txt_AvlAmount, txt_Balance, txt_WithdrawAmount});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_withdrawActionPerformed

        try {
            int i = JOptionPane.showConfirmDialog(rootPane, "Are you sure, you want to withdraw money now ?", "Withdraw Money", 0);
            if (i == 0) {
                // save withdraw record
                JDBC.putData("INSERT INTO withdraw VALUES('0' , '" + payeeAccID + "' , '" + txt_WithdrawAmount.getText() + "' , '" + Home.adminUserID + "' , '" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()).toString() + "' , '" + new SimpleDateFormat("hh:mm:ss a").format(new Date()).toString() + "'   ) ");
                // Update payee account balance amount
                JDBC.putData(" UPDATE payee_account SET balance = '" + txt_Balance.getText() + "' WHERE payee_account_id = '" + payeeAccID + "' ");
                JOptionPane.showMessageDialog(rootPane, "Withdraw Transaction Successful!");
                this.dispose();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_withdrawActionPerformed

    private void txt_WithdrawAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_WithdrawAmountKeyTyped

        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            if (key != '.') {
                evt.consume();
            }
        }
        if (key == KeyEvent.VK_PERIOD) {
            if (txt_WithdrawAmount.getText().trim().contains(".")) {
                evt.consume();
            }
        }
        if (txt_WithdrawAmount.getText().length() == 15) {
            evt.consume();
        }

    }//GEN-LAST:event_txt_WithdrawAmountKeyTyped

    private void txt_WithdrawAmountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_WithdrawAmountFocusLost

        final DecimalFormat df = new DecimalFormat("#0.00");
        if (txt_WithdrawAmount.getText().trim().isEmpty()) {
            txt_WithdrawAmount.setText("0");
        }
        if (txt_WithdrawAmount.getText().trim().equals(".")) {
            txt_WithdrawAmount.setText("0");
        }
        txt_WithdrawAmount.setText(df.format(Double.parseDouble(txt_WithdrawAmount.getText().trim())));
        calcBalance();

    }//GEN-LAST:event_txt_WithdrawAmountFocusLost

    private void txt_WithdrawAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_WithdrawAmountKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_withdraw.grabFocus();
        }

    }//GEN-LAST:event_txt_WithdrawAmountKeyPressed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed

        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_WithdrawAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_WithdrawAmountKeyReleased

        calcBalance();

    }//GEN-LAST:event_txt_WithdrawAmountKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seller_Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seller_Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seller_Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seller_Withdraw.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Seller_Withdraw dialog = new Seller_Withdraw(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_background;
    private javax.swing.JPanel Panel_header;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_withdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txt_AvlAmount;
    private javax.swing.JLabel txt_Balance;
    private javax.swing.JTextField txt_WithdrawAmount;
    // End of variables declaration//GEN-END:variables

    private void calcBalance() {
        try {
            // check withdraw amount is empty OR not
            if (txt_WithdrawAmount.getText().toString() == null | txt_WithdrawAmount.getText().toString().isEmpty()) {
                txt_Balance.setText(txt_AvlAmount.getText());
                btn_withdraw.setEnabled(false);  // Disable Withdraw
                btn_withdraw.setBackground(new Color(240, 240, 240));
            } else {
                // revoke unecessary input values
                if (txt_WithdrawAmount.getText().toString().trim().equals(".")) {
                    btn_withdraw.setEnabled(false);  // Disable Withdraw
                    btn_withdraw.setBackground(new Color(240, 240, 240));
                } else {
                    txt_Balance.setText(String.valueOf(new DecimalFormat("#0.00").format(Double.valueOf(txt_AvlAmount.getText()) - Double.valueOf(txt_WithdrawAmount.getText()))));
                    // Check if Withdraw Amount > Available Amount
                    if (Double.valueOf(txt_WithdrawAmount.getText()) > Double.valueOf(txt_AvlAmount.getText())) {
                        btn_withdraw.setEnabled(false);  // Disable Withdraw
                        btn_withdraw.setBackground(new Color(240, 240, 240));
                    } else {
                        // Check if Withdraw Amount == 0.00
                        if (Double.valueOf(txt_WithdrawAmount.getText()) == 0.00) {
                            btn_withdraw.setEnabled(false);  // Disable Withdraw
                            btn_withdraw.setBackground(new Color(240, 240, 240));
                        } else {
                            btn_withdraw.setEnabled(true);  // Enable Withdraw
                            btn_withdraw.setBackground(new Color(0, 125, 184));
                        }
                    }
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
